### ISSUE TITLE
default fuse-bit values

### ISSUE THREAD

**Issue by allardlamberink** [TheThingsProducts/node#3]
I've bricked my The Things Node device, and I've already followed all the un-brick instructions, but nothing works so far. The red-led is flashing slowly during startup, but I'm not able to actually program the "Node". I've been messing around with the fuse-bits and now I'm looking around for the factory-default fuse-bit configuration for The Things Node. Can somebody please list the default values for lfuse, hfuse and efuse?

**Comment by allardlamberink** [comment]
anyone? Maybe it's an option if I can "borrow" another "the things node" device to find out the default settings myself?

**Comment by svenhaitjema** [comment]
Dear Allard,

Fusebits are critical for the operation for your node. I strongly advise
you to not touch any fuse settings, and if you do, run a backup. The fuses
should be:
lowBits =           0xFF
highBits =         0xD8
extendedBits=  0xF7
lockBits =          0xCF

Kind regards,

Sven-Erik Haitjema

On Fri, Apr 20, 2018 at 12:14 PM, Allard Lamberink <notifications@github.com
