### ISSUE TITLE
Our experience with The Things Node FW

### ISSUE THREAD

**Issue by JDC-CPS** [TheThingsProducts/node#4]
We recently purchased two The Things Node LoRa devices, and we have been evaluating them in their different versions of FW Arduino they offer. The truth is that the stability or reliability leaves much to be desired: crashes o hangs often or appear failures in communications.
Do not have other evolutions of the FW more evolved and stable ?.
Is it necessary to have a deep knowledge of the RN2483 module (inside) and its configuration to integrate the devices reliably ?.

RN version used is 1.0.3
It reports these traces:
**Response is not OK: no_free_ch
Send command failed**

**Comment by johanstokking** [comment]
@JDC-CPS that error means that the end device has no free channel available to send, most often due to duty cycle limitations.

The library is a wrapper around the RN2xx3 commands, see [here](http://ww1.microchip.com/downloads/en/DeviceDoc/40001784B.pdf), also with explanation of error codes.

**Comment by JDC-CPS** [comment]
Thanks for you answer, but the traffic generated was very lower (Basic FW example with periodic message every minute). I think that, with this frequency of messages and , is not normal. Also with free spectrum around our site.
However, I insist, Basic or Cayenne demos crashes o hangs often.

**Comment by johanstokking** [comment]
In fact it's quite easy to exceed duty cycle limitations. Note that this is enforced by the RN module on the board; not by the library and not by the network. Also it doesn't do a spectrum scan (listen before talk), which is permitted by ETSI regulations as an alternative to duty cycle, but LoRaWAN PHY uses duty cycle exclusively, so the availability of free spectrum is not relevant.

If you have specific issues with the Basic or Cayenne examples, a trace log, etc, please reopen and provide additional information that allows others to find the cause. I'm myself not aware of any instability issues with the libraries.
